development:
  adapter: postgresql
  encoding: unicode
  database: zen_challenge_development
  pool: 5
  username:
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: zen_challenge_test
  pool: 5
  username:
  password:

production:
  adapter: postgresql
  encoding: unicode
  database: zen_challenge_production
  pool: 5
  username:
  password:
